### ISSUE TITLE
ModuleNotFoundError when using ReceiverFunctionInversionShibutani

### ISSUE THREAD

**Issue by fmagrini** [inlab-geo/cofi-examples#38]
examples/receiver_function/receiver_function_inversion.ipynb fails at the line

        my_receiver_function = espresso.ReceiverFunctionInversionShibutani(example_number=4)

 giving the following error

        ModuleNotFoundError                       Traceback (most recent call last)
        ~/mambaforge/envs/seislib/lib/python3.9/site-packages/espresso/_receiver_function_inversion_shibutani/rf.py in <module>
             16 try:
        ---> 17     from .build import rfc as rfm # if file is only to be used as library
             18 except:

        ModuleNotFoundError: No module named 'espresso._receiver_function_inversion_shibutani.build'

        During handling of the above exception, another exception occurred:

        ModuleNotFoundError                       Traceback (most recent call last)
        /tmp/ipykernel_43816/3476467975.py in <cell line: 1>()
        ----> 1 my_receiver_function = espresso.ReceiverFunctionInversionShibutani(example_number=4)

        ~/mambaforge/envs/seislib/lib/python3.9/site-packages/espresso/_receiver_function_inversion_shibutani/_receiver_function_inversion_shibutani.py in __init__(self, example_number)
             42         super().__init__(example_number)
             43 
        ---> 44         from . import rf
             45         self.rf = rf
             46 

        ~/mambaforge/envs/seislib/lib/python3.9/site-packages/espresso/_receiver_function_inversion_shibutani/rf.py in <module>
             17     from .build import rfc as rfm # if file is only to be used as library
             18 except:
        ---> 19     from build import rfc as rfm # if file is to be executed
             20 import numpy as np
             21 #matplotlib.use('Qt4Agg')

**Comment by msambridge** [comment]
I think this is now solved with the switch to the new implementation pyrf96, as we're no longer using the internal build of Shibutani's code via f2py. @auggiemarignier has redirected the espresso _receiver_function_inversion_shibutani forward code to the ctypes version pyrf96  Can we agree to close this?

**Comment by fmagrini** [comment]
Yeah, I'll close it for now as this appears to be fixed

**Comment by auggiemarignier** [comment]
This Shibutani problem should be resolved at this point, but I can foresee the same problems for the Kennett and the FMM until they also get wrapped in their own external packages.

Happy to close this issue now.
