### ISSUE TITLE
`pysurf96` now on PyPI

### ISSUE THREAD

**Issue by auggiemarignier** [inlab-geo/cofi-examples#44]
The original `f2py`-wrapped version of `surf96` is now available on [`pypi`](https://pypi.org/project/pysurf96/).

@JuergHauser do we want to keep using our `ctypes` fork?

**Comment by auggiemarignier** [comment]
They only seem to have wheels for linux so this wouldn't always get us around the `f2py` issues.

**Comment by JuergHauser** [comment]
I think we want to keep our ctypes fork but if someone else is maintaining  a version that works let's use their versions. I did try `pip install pysurf96` and it works on my mac just fine. I will update our readme to make clear how our fork is different.

**Comment by auggiemarignier** [comment]
OK, and so for `cofi-examples` we'll keep using the `ctypes` wrapper.  Since `cofi-examples` isn't going on pypi this shouldn't be a problem.  If we do a surface wave `espresso` we'll have to either push our `ctypes` wrapper to `pypi` or use the `f2py` wrapper that's already there.
